### PR TITLE
Add ntfy support.

### LINKED ISSUE #1: Ntfy support(for the F-Droid variant of Amethyst)
This issue is here mostly to track the status of the implementation of UnifiedPush/Ntfy support with/until the PR that will come along.

### PR DESCRIPTION
**Pull request by KotlinGeekDev**
Fixes #1 .
The approach I used is saving the push endpoint URL directly into the DB as a token, but differentiate the token characteristics when sending notifications.

### CODE REVIEW

**Comment by KotlinGeekDev** [comment]
cc @vitorpamplona

**Comment by vitorpamplona** [comment]
When I merge this it goes live immediately, so we need to make sure it works. 

We shouldn't call the Google version of Notify if there are no tokens that are not URLs. I would move the added filter 

```js
tokens.filter(function (url){ !isValidUrl(url) })
```

earlier and only call each service (Nfty or Google) on its own token set and don't call it if the list is empty.

**Comment by KotlinGeekDev** [comment]
> When I merge this it goes live immediately, so we need to make sure it works.
> 
> We shouldn't call the Google version of Notify if there are no tokens that are not URLs. I would move the added filter
> 
> ```js
> tokens.filter(function (url){ !isValidUrl(url) })
> ```
> 
> earlier and only call each service (Nfty or Google) on its own token set and don't call it if the list is empty.

@vitorpamplona OK I see what you mean.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona done.

**Comment by KotlinGeekDev** [comment]
Will test the code (again) and report here.

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona in the getAllRelays() function, I see a votes variable, but I don't understand it's role. EDIT: Understood now, but still asking myself if it is necessary.

**Comment by KotlinGeekDev** [comment]
Side note: the tests went very well!

**Comment by vitorpamplona** [comment]
> Please @vitorpamplona in the getAllRelays() function, I see a votes variable, but I don't understand it's role. EDIT: Understood now, but still asking myself if it is necessary.

It's a bad variable name but it essentially counts how many times each relay is used and only connects to relays that have 2 or more users. That removes all personal relays and private stuff people have.

**Comment by KotlinGeekDev** [comment]
> > Please @vitorpamplona in the getAllRelays() function, I see a votes variable, but I don't understand it's role. EDIT: Understood now, but still asking myself if it is necessary.
> 
> It's a bad variable name but it essentially counts how many times each relay is used and only connects to relays that have 2 or more users. That removes all personal relays and private stuff people have.

OK, it means we're good then. The PR can be merged.

**Comment by vitorpamplona** [comment]
nice!  I will do a quick review and merge tomorrow :)

**Comment by KotlinGeekDev** [comment]
> nice! I will do a quick review and merge tomorrow :)

OK :)

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona any updates on this? :sweat_smile:

**Comment by vitorpamplona** [comment]
Thanks @KotlinGeekDev !

**Comment by KotlinGeekDev** [comment]
:+1:

**Comment by vitorpamplona** [comment]
Server is online. Now let's test if the F-Droid flavor works :)

**Comment by KotlinGeekDev** [comment]
@vitorpamplona yeah :)

**Pull request merged**
